// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3jLGGGJqaU2NaxJstGNCUjhWMt7Kubck',
    appId: '1:298033113736:web:58c84d1fa7d256a9454d3d',
    messagingSenderId: '298033113736',
    projectId: 'binaural-beats-a6d55',
    authDomain: 'binaural-beats-a6d55.firebaseapp.com',
    databaseURL: 'https://binaural-beats-a6d55-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'binaural-beats-a6d55.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3PoYjC1TebBwBNSg7u7BHjY9L_sox2YU',
    appId: '1:298033113736:android:bbf2751a46fb6758454d3d',
    messagingSenderId: '298033113736',
    projectId: 'binaural-beats-a6d55',
    databaseURL: 'https://binaural-beats-a6d55-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'binaural-beats-a6d55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNOPk7u2_DUBuuV8nUbLMfsK6HqbG0kJ0',
    appId: '1:298033113736:ios:9d9eff335f78b683454d3d',
    messagingSenderId: '298033113736',
    projectId: 'binaural-beats-a6d55',
    databaseURL: 'https://binaural-beats-a6d55-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'binaural-beats-a6d55.appspot.com',
    iosBundleId: 'com.example.beats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNOPk7u2_DUBuuV8nUbLMfsK6HqbG0kJ0',
    appId: '1:298033113736:ios:0cda5dd2cd1c7784454d3d',
    messagingSenderId: '298033113736',
    projectId: 'binaural-beats-a6d55',
    databaseURL: 'https://binaural-beats-a6d55-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'binaural-beats-a6d55.appspot.com',
    iosBundleId: 'com.example.beats.RunnerTests',
  );
}
